// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Animals struct {
	ID   string `json:"_id" bson:"_id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type NewAnimal struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
